services:
  db:
    image: postgres:15
    container_name: fitnes_man-db-1
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fitnes_man_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p ${PORT:-3000} -b 0.0.0.0"
    container_name: fitnes_man_container
    tty: true
    stdin_open: true
    volumes:
      - .:/fitnes_man
    environment:
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      DATABASE_URL: "postgres://postgres:password@db:5432/fitnes_man_test"
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      RAILS_MAX_THREADS: 20
      GOOGLE_REDIRECT_URI: http://localhost:3000/users/auth/google_oauth2/callback
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      db:
        condition: service_healthy
      chrome:
        condition: service_started
  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4444:4444
volumes:
  postgres_data:
  bundle_data:
  node_modules:
