services:
  db:
    image: mysql:8.0
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p ${PORT:-3000} -b 0.0.0.0"
    container_name: fitnes_man_container
    tty: true
    stdin_open: true
    volumes:
      - .:/fitnes_man
      # - bundle_data:/usr/local/bundle:cached
    environment:
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      RAILS_ENV: production
      SECRET_KEY_BASE: your_generated_secret_key_here
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - db
      - chrome
  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4444:4444
volumes:
  mysql_data:
  bundle_data:
  node_modules:
