databases:
  - name: fitnes_man_db
    databaseName: fitnes_man_production
    user: fitnes_man_user
    region: singapore
    ipAllowList: []  # すべてのIPを許可（必要に応じて制限）

services:
  - type: web
    name: fitnes_man_app
    runtime: ruby  # ✅ runtime を追加（Rubyを指定）
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fitnes_man_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: PORT
        value: "3000"
